name: Test project

on:
    push:
        branches: [master]

jobs:
    prepare:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm i --save-dev @types/node
            - run: npm i sslkeylog
            - run: npm run prepare-windows
            - run: del settings.json
            - run: node lib/tests.js "${{ secrets.TOKEN }}" "${{ secrets.PLACEID }}"
