name: Production Test Windows Server 2019

on:
    push:
        paths:
          - 'src/**'
          - '.github/workflows/**'

jobs:
    info-logger:
        runs-on: windows-latest
        steps:
           - name: Logger
             run: "echo \"Job(%GITHUB_JOB%-%GITHUB_ACTION%): Running workflow \\\"%GITHUB_WORKFLOW%\" with ID \\\"%GITHUB_RUN_ID%\\\" and number \\\"%GITHUB_RUN_NUMBER%\\\"\""

    production-test:
        runs-on: windows-latest
        steps:
            - name: Checkout repository.
              uses: actions/checkout@v2

            - name: Setup the node js environment with version 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install the lastest node-js types for typescript.
              run: npm i --save-dev @types/node

            - name: Run the prepare script to update packages and build the project.
              run: npm run prepare
            
            - name: Run the tests.js file to test the datastores.
              run: node lib/tests.js "${{ secrets.TOKEN }}" "${{ secrets.PLACEID }}" "${{ secrets.UNIVERSEID }}" "${{ secrets.USERID }}" "${{ secrets.USERNAME }}"
